### ISSUE TITLE
Different Carla versions

### ISSUE THREAD

**Issue by lcipolina** [praveen-palanisamy/macad-gym#22]
Hi, this is not an issue but more like a question.

I see that this library works with Carla  0.9.4, however, I also need to have version 0.9.6 installed as I am using its newest functionality with SUMO. This creates a conflict when I try to use this library.

**Is there a way I can have both versions installed on my machine without conflicting with your library?**

Maybe having 2 different PATHS env variables on the .bashrc ?

Thanks!

**Comment by praveen-palanisamy** [comment]
Hi @lcipolina ,

Yes. You can `export CARLA_SERVER="/PATH/TO/CARLA_0.9.4/CarlaUE4.sh"` to run MACAD-Gym
and then you can either :
 1.  use a different environment variable (instead of `CARLA_SERVER`) or
 2.  preprend/reset the value of `CARLA_SERVER` to 0.9.6 when you run your scripts that depend on the SUMO functionality.

Summary:
1.  `export CARLA_SERVER_096="PATH/software/CARLA_0.9.6/CarlaUE4.sh"`  or
2.  `CARLA_SERVER="PATH/software/CARLA_0.9.6/CarlaUE4.sh" python your_script_that_depends_on_sumo.py"`

The alter

**Comment by lcipolina** [comment]
Very clear. 

I believe this question will help other people as well.
I will close the question as I have been answered.
Thank you very much!
