### ISSUE TITLE
Support for CARLA built from source

### ISSUE THREAD

**Issue by Neel1302** [praveen-palanisamy/macad-gym#23]
Hi @praveen-palanisamy. Thanks for your great work.

I have built carla 0.9.9 from source. Is there a way to run your code with it? Since I built carla from source, it does not have a CarlaUE4.sh file in which case it does not make sense to set CARLA_SERVER.

If I launch CARLA from UE4 using make launch and then open up a specific town, is it possible to point to this instance in your code?

Thanks,
Neel

**Comment by praveen-palanisamy** [comment]
Hi @Neel1302 ,

**Short answer:** Use `make package` (instead of `make launch`) to generate the packaged version of CARLA built from source. This will generate the `CarlaUE4.sh` that you can point to with`CARLA_SERVER`.

**Long answer:**
Yes. It is possible to build CARLA from source and use it with MACAD-Gym. Whether you build and packaged it from source or use the binary packaged version, the CARLA server, being an UnrealEngine 4 project should generate the bash script file (`CarlaUE4.sh`) that runs the executable binary. (It may not be called `CarlaUE4.sh` if you customized the UE4 project name).

>INFO: `make launch` essentially translates to: ${UE4_ROOT}/Engine/Binaries/Linux/UE4Editor "${PWD}/CarlaUE4.uproject"

When you use `make launch`, it will launch the Carla project inside the UE4 editor. This adds a lot of overhead and reduces the performance due to the UE4 editor so this is not a preferred way of launching CARLA especially for RL agent training which is the main use case of [MACAD-Gym](https://github.com/praveen-palanisamy/macad-gym). The preferred way of launching CARLA sim server for RL training purposes is using the optimized, packaged binary version.

If you have a real need for being able to run the CARLA server with the editor for training, please describe your use-case so that I can understand it better to support it.

Hope that helps.

**Comment by Neel1302** [comment]
@praveen-palanisamy 

Thanks for that. I was still getting errors when I tried using make package.

So instead, I installed carla 0.9.8. I have setup the CARLA_SERVER env variable as well as made sure the python api version is 0.9.8.

Running the example agent script launches carla, but there isn't any pygame window or actors appearing. Do you have any ideas?
![image](https://user-images.githubusercontent.com/8161543/89127243-12a48980-d4ba-11ea-99c1-aa77bdec8411.png)

**Comment by praveen-palanisamy** [comment]
Glad that it's working for you with the `0.9.4` release version. Currently, that's the tested and fully supported version. Changes in later versions of CARLA that broke compatibility with v`0.9.4` will cause issues.

CARLA is undergoing several changes too as it is approaching the major release (1.0). I have a to-do item created for this project to support CARLA 1.0 when it's ready/released. Depending on my bandwidth, I will also try to support the pre-release versions. Contributions are very welcome and I can help!

I'm closing this issue since the original issue has been addressed. Feel free to re-open or open new issues as necessary.
