### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by lijecaru** [praveen-palanisamy/macad-gym#3]
What are the algorithms included? Do you maybe have some tutorial or documentation to test it? Thank you!

**Comment by praveen-palanisamy** [comment]
Hi @lijecaru :

There is a ["Getting Started" section in the README file](https://github.com/praveen-palanisamy/macad-gym#getting-started) and the typical usage of the environments provided by the macad-gym package is illustrated [here](https://github.com/praveen-palanisamy/macad-gym#learning-platform-and-agent-interface).

As an example, after you setup CARLA 0.9.x and install macad-gym using the [instructions in the README.md](https://github.com/praveen-palanisamy/macad-gym#getting-started), You can find the list of available learning environments and a brief description of the environments using the following 3 lines of code:

```python
import gym
import macad_gym
macad_gym.get_available_envs()
```
Let's say you want to use the `HomoNcomIndePOIntrxMASS3CTWN3-v0` environment, you can then create an environment using the following 3 lines of code:
```python
import gym
import macad_gym
env = gym.make("HomoNcomIndePOIntrxMASS3CTWN3-v0")
```

These learning environments are OpenAI Gym compatible. Therefore, you can use any standard RL/deep-RL library to train you agents in these environments.
Let me know if you need more information to get started.

**Comment by lijecaru** [comment]
@praveen-palanisamy I tried to use macad-gym in the both ways described in the README file. 

1. Installing it as only a user (pip install git+https://github.com/praveen-palanisamy/macad-gym.git) doesn't provide any error when I run the line `import macad_gym`, but when I test `macad_gym.get_available_envs()` I the following message: `AttributeError: module 'macad_gym' has no attribute 'get_available_envs'`

2. As a developer, I create the conda environment using the .yaml file, but when I ran again `import macad_gym` I get the following: `ModuleNotFoundError: No module named 'macad_gym'`

I am using Ubuntu 16.04 and Anaconda3. Any idea of what I could do to solve this? Thank you

**Comment by praveen-palanisamy** [comment]
Hi @lijecaru, 
You actually had them all right! The function name to get the list of available environments in the latest version is: `list_available_envs`. So, please use: `macad_gym.list_avaialble_envs()` and it should work.

Thanks for reporting this. I have updated the README to reflect the change as per the latest version. The reason why you get `ModuleNotFoundError: No module named 'macad_gym'` in your case 2. is because, you might have not installed the `macad-gym` package. You can use: `pip install -e .` from the `macad-gym` folder after you have cloned this repo. I have updated the README to reflect this as well.

Hope that gets you rolling. Let me know if you face any other issue.
