### ISSUE TITLE
Also stuck in env.reset() in example

### ISSUE THREAD

**Issue by KID0031** [praveen-palanisamy/macad-gym#63]
Hi, when I tried to example code run `basic_agent.py`, the terminal only output this and then stuck in code `env.reset()`
![image](https://user-images.githubusercontent.com/51467434/164885995-7fd43075-b9a5-47cc-a8ed-786ab59b787e.png)
I tried both Carla 0.9.4 and 0.9.12, they have the same problem. the system is ubuntu 20.0.4 and python 3.8
the log in `example/log/macad_gym.log` is like this and there is no bug
![image](https://user-images.githubusercontent.com/51467434/164886100-4be8aab1-bb2b-4fa1-8c8f-eb17aac101a7.png)
Is there any way I can fix this issue? Thanks a lot :)

**Comment by praveen-palanisamy** [comment]
Hi @KID0031,
From the log it looks like the CARLA server was not launched on your machine for some reason. I am assuming that you have followed the [setup steps described here](https://github.com/praveen-palanisamy/macad-gym#getting-started).
Could you share your output for: `echo $CARLA_SERVER`?
Also, are you able to execute: ` bash $CARLA_SERVER` without any issues?

**Comment by Morphlng** [comment]
I'm also having this problem; the only difference is that I'm using Windows.

By following another issue ([Windows Support workaround](https://github.com/praveen-palanisamy/macad-gym/issues/32#issuecomment-779564218)), I'm finally able to run the example in readme without error output. But I'm stuck at `obs = env.reset()`, since I can see that CarlaUE4 is on (with window popping up), I don't think it's that "CARLA server wasn't launch problem". Also, `bash $CARLA_SERVER` isn't going to work on Windows, but the equivalent line `%CARLA_SERVER%` can indeed open CarlaUE4

The environment details I'm using is as below:
1. Windows 11 latest build
2. Carla 0.9.13 pre-built release (since the issuer said falling back to 0.9.4 doesn't help, I'm not going to try that now)
3. Carla Python API 0.9.13_cp38 from [pypi.prg](https://pypi.org/project/carla/#files)

> Hi @KID0031, From the log it looks like the CARLA server was not launched on your machine for some reason. I am assuming that you have followed the [setup steps described here](https://github.com/praveen-palanisamy/macad-gym#getting-started). Could you share your output for: `echo $CARLA_SERVER`? Also, are you able to execute: ` bash $CARLA_SERVER` without any issues?

**Comment by praveen-palanisamy** [comment]
@KID0031 : Please try the latest version with MorphIng's fixes, which likely resolves the issue you are facing. You would want to clone [this](https://github.com/praveen-palanisamy/macad-gym) repo, pull the latest changes and install the python package from source using: `pip install -e .`

I am closing this issue based on MorphIng's PR comments & fixes. Please re-open if you are still facing this issue.
